### PR TITLE
mv cmd/main.go main.go

### PR DESCRIPTION
**Pull request by gregf**
This allows users to use go get -u github.com/ftpgrab/ftpgrab to
install from source more easily. It also let's use package goftp
more easily on FreeBSD and most likely other operating systems.

### CODE REVIEW

**Comment by crazy-max** [comment]
I prefer to keep this project layout to _respect standard_.
Yeah it's kinda [unofficial](https://github.com/golang-standards/project-layout) :upside_down_face: but big go projects in the wild use this nomenclature :

* https://github.com/heptio/ark/tree/master/cmd
* https://github.com/moby/moby/tree/master/cmd
* https://github.com/prometheus/prometheus/tree/master/cmd
* https://github.com/influxdata/influxdb/tree/master/cmd
* https://github.com/kubernetes/kubernetes/tree/master/cmd

And you can always use `go get -u github.com/ftpgrab/ftpgrab/cmd` to install from source.

**Comment by crazy-max** [comment]
@gregf Keep in touch, I encountered an issue with `go get -u`, see russross/blackfriday#491

I will update go.mod to solve this :

`go mod edit -replace=gopkg.in/russross/blackfriday.v2@v2.0.1=github.com/russross/blackfriday/v2@v2.0.1`

**Comment by gregf** [comment]
Any chance I can get you to vendor your go mods in a vendor directory? It makes things for my FreeBSD package way simpler to maintain and personally I believe everything should be vendor anyways, I do it in my projects.

**Comment by crazy-max** [comment]
@gregf Since Go 1.11 I prefer to drop vendoring entirely. Please read this [official thread](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away) about it. You can use `go mod vendor` to reset the main module's vendor directory to include all packages needed to build if you want or maybe we could create a side repository to put vendoring in it and create a git submodule in this repository but I'm not a huge fan.

**Comment by gregf** [comment]
I got the port working finally, I'll link you to the pr tomorrow

**Comment by crazy-max** [comment]
@gregf I close this PR, please open a new one relative to FreeBSD if you want. Thanks!

**Pull request closed without merging**
